<a href="https://colab.research.google.com/github/detayans/PandasAssignment/blob/main/PandasAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#1) Generate an array of zeroes using inbuilt numpy function.
a = np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
#2) Run the given code and find the dot product of both arrays.
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[6 4 4 8]
 [8 3 9 2]
 [7 9 4 7]]
[[6 7 7]
 [7 2 9]
 [4 2 4]
 [4 5 6]]


In [ ]:
a.dot(b)

array([[112,  98, 142],
       [113,  90, 131],
       [149, 110, 188]])

In [ ]:
b.dot(a)

array([[141, 108, 115, 111],
       [121, 115,  82, 123],
       [ 68,  58,  50,  64],
       [106,  85,  85,  84]])

In [ ]:
#3)Read the csv file provided using pandas and display the first 5 entries
import pandas as pd


In [ ]:
data = pd.read_csv('/content/data.csv')
data.head(5)

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

In [ ]:
#4)Describe the data with all features.
data

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0         21                   Fort Stevenson State Park  ...   0.000284   0.135641
1         22                      Beaver Lake State Park  ...   0.000129   0.080067
2         23             Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3         24                      Fort Ransom State Park  ...   0.000444   0.128733
4         25                   Grahams Island State Park  ...   0.000469   0.125546
5         26                        Icelandic State Park  ...   0.000461   0.166712
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
7         28                  Lewis and Clark State Park  ...   0.000256   0.130420
8         29         Lewis and Clark Interpretive Center  ...   0.000007   0.016774
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396
10        31                  Little Missouri State Park  ...   0.003136   0.313756
11        32                      Sully Creek State Park  ...   0.000030   0.024016
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
14        33                     Turtle River State Park  ...   0.000378   0.145220
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
20        41           Missouri River State Natural Area  ...   0.000083   0.087192
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
23        45                      Cross Ranch State Park  ...   0.000274   0.180257
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357

[25 rows x 6 columns]

In [ ]:
data.shape

(25, 6)

In [ ]:
#5)Find the total count of missing values for each feature.
missing_value = data.isna().sum()
missing_value

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [ ]:
#6)Display all the unique values from the 'DESCRIPTION’ column.
data['DESCRIPTION'].value_counts()


State Park               13
State Recreation Area     7
State Nature Preserve     2
State Natural Area        2
Interpretive Center       1
Name: DESCRIPTION, dtype: int64

In [ ]:
data['UNIT_NAME'].value_counts()

Lake Metigoshe State Park                     1
Fort Stevenson State Park                     1
Butte St. Paul State Recreation Area          1
Turtle Mountain State Recreation Area         1
Pelican Point State Recreation Area           1
Fort Abraham Lincoln State Park               1
Icelandic State Park                          1
Fort Mandan State Recreation Area             1
Little Missouri State Park                    1
Beaver Lake State Park                        1
Elkhorn State Natural Area                    1
Head of the Mountain State Nature Preserve    1
Lake Sakakawea State Park                     1
Gunlogson State Nature Preserve               1
Sully Creek State Park                        1
Lewis and Clark Interpretive Center           1
Turtle River State Park                       1
Cross Ranch State Park                        1
Fort Ransom State Park                        1
Fahlgren Park State Recreation Area           1
Missouri River State Natural Area       

In [ ]:
data['ACRES'].value_counts()

6492.93    1
14.71      1
21.56      1
247.11     1
273.16     1
51.23      1
264.84     1
1236.98    1
739.52     1
174.39     1
1508.53    1
524.81     1
586.48     1
569.07     1
695.04     1
63.03      1
95.89      1
933.78     1
930.30     1
25.22      1
836.47     1
11.40      1
72.30      1
775.28     1
959.33     1
Name: ACRES, dtype: int64

In [ ]:
data['SHAPE.AREA'].value_counts()

0.000083    1
0.003136    1
0.000461    1
0.000127    1
0.000005    1
0.000399    1
0.000274    1
0.000357    1
0.000034    1
0.000469    1
0.000284    1
0.000120    1
0.000048    1
0.000378    1
0.000256    1
0.000751    1
0.000010    1
0.000025    1
0.000013    1
0.000030    1
0.000345    1
0.000129    1
0.000444    1
0.000007    1
0.000615    1
Name: SHAPE.AREA, dtype: int64

In [ ]:
data['SHAPE.LEN'].value_counts() 

0.087192    1
0.067082    1
0.130420    1
0.026357    1
0.119868    1
0.016774    1
0.125546    1
0.050518    1
0.024016    1
0.009396    1
0.033885    1
0.212196    1
0.338800    1
0.135641    1
0.191806    1
0.086487    1
0.145220    1
0.180257    1
0.022095    1
0.166712    1
0.128733    1
0.080067    1
0.313756    1
0.040465    1
0.013294    1
Name: SHAPE.LEN, dtype: int64

In [ ]:
#7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.
data.groupby('DESCRIPTION').OBJECTID.mean()

DESCRIPTION
Interpretive Center      29.000000
State Natural Area       39.000000
State Nature Preserve    39.500000
State Park               28.538462
State Recreation Area    38.285714
Name: OBJECTID, dtype: float64

In [ ]:
data.groupby('DESCRIPTION').UNIT_NAME.count()

DESCRIPTION
Interpretive Center       1
State Natural Area        2
State Nature Preserve     2
State Park               13
State Recreation Area     7
Name: UNIT_NAME, dtype: int64

In [ ]:
data.groupby('DESCRIPTION').ACRES.mean()

DESCRIPTION
Interpretive Center        14.710000
State Natural Area        219.615000
State Nature Preserve      84.095000
State Park               1168.668462
State Recreation Area     326.934286
Name: ACRES, dtype: float64

In [ ]:
#8)Generate a random sample of 10 rows from the data.
a = np.random.rand(10)
a

array([5.16881219e-04, 9.11515995e-02, 4.33012008e-02, 6.57817846e-01,
       7.94118755e-01, 9.48346454e-01, 3.85399571e-01, 1.74419288e-01,
       7.17055344e-01, 7.98082897e-01])

In [ ]:
#9)Add a Feature called 'New_feature' to the new Dataset and 
#Add Random float Values in between 0 and 1 using Numpy.
new_feature = np.random.rand(5)
new_feature

array([0.32320436, 0.24940288, 0.7631069 , 0.47126091, 0.72700391])

In [94]:
New_feature=np.random.rand(25,1)
data['New_feature']=New_feature
data


OBJECTID  ... New_feature
0         21  ...    0.341396
1         22  ...    0.540432
2         23  ...    0.537432
3         24  ...    0.017064
4         25  ...    0.183358
5         26  ...    0.644172
6         27  ...    0.059727
7         28  ...    0.666799
8         29  ...    0.696688
9         30  ...    0.666568
10        31  ...    0.018096
11        32  ...    0.450074
12        35  ...    0.423447
13        36  ...    0.393027
14        33  ...    0.364341
15        34  ...    0.459612
16        37  ...    0.596649
17        38  ...    0.975819
18        39  ...    0.930112
19        40  ...    0.728065
20        41  ...    0.630890
21        43  ...    0.234431
22        44  ...    0.467119
23        45  ...    0.534654
24        42  ...    0.420329

[25 rows x 7 columns]

In [96]:
#10) Replace zero value of column 'OBJECTID' with mean value permanently.
mean_value=data['OBJECTID'].mean()

In [98]:
data[pd.isnull(data.OBJECTID)]
data.OBJECTID.fillna(mean_value)



0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64